#!/usr/bin/env python3
"""Apply FoxxDesk runtime defaults without modifying the hbb_common submodule.

This helper keeps all FoxxDesk-specific defaults in the parent repository so they
survive a clean recursive submodule checkout in GitHub Actions. Patches are small,
marker-based and fail early when an upstream source layout changes materially.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from foxxdesk_config import load_config  # noqa: E402

SCRIPT_VERSION = "foxxdesk-runtime-defaults-v1-submodule-safe-2026-09-05"
MARK = "FOXXDESK_RUNTIME_DEFAULTS_V1"


class PatchError(RuntimeError):
    pass


def rust_string(value: str) -> str:
    return value.replace('\\', '\\\\').replace('"', '\\"')


def expected_defaults_source(cfg: dict) -> str:
    brand = cfg['brand']
    network = cfg['network']
    display = rust_string(str(brand['display_name']))
    server = rust_string(str(network['server']))
    relay = rust_string(str(network.get('relay') or network['server']))
    key = rust_string(str(network['key']))
    return f'''// {MARK}\n// Generated by scripts/foxxdesk_runtime_defaults.py.\n// Keep FoxxDesk defaults in the parent crate; do not patch libs/hbb_common.\n\nuse hbb_common::config;\nuse std::sync::Once;\n\npub const APP_NAME: &str = "{display}";\npub const RENDEZVOUS_SERVER: &str = "{server}";\npub const RELAY_SERVER: &str = "{relay}";\npub const PUBLIC_KEY: &str = "{key}";\n\nstatic APPLY: Once = Once::new();\n\npub fn apply() {{\n    APPLY.call_once(|| {{\n        *config::APP_NAME.write().unwrap() = APP_NAME.to_owned();\n        *config::PROD_RENDEZVOUS_SERVER.write().unwrap() = RENDEZVOUS_SERVER.to_owned();\n    }});\n}}\n'''


def replace_once(text: str, old: str, new: str, label: str) -> tuple[str, bool]:
    if new in text:
        return text, False
    if old not in text:
        raise PatchError(f"{label}: anchor upstream não encontrado")
    return text.replace(old, new, 1), True


def patch_lib_rs(text: str) -> tuple[str, bool]:
    if 'mod foxxdesk_defaults;' in text:
        return text, False
    anchors = ['use common::*;\n', 'mod custom_server;\n']
    for anchor in anchors:
        if anchor in text:
            return text.replace(anchor, anchor + 'mod foxxdesk_defaults; // ' + MARK + '\n', 1), True
    raise PatchError('src/lib.rs: não foi possível inserir mod foxxdesk_defaults')


def patch_common_rs(text: str) -> tuple[str, bool]:
    changed = False
    global_marker = f'pub fn global_init() -> bool {{\n    crate::foxxdesk_defaults::apply(); // {MARK}'
    if global_marker not in text:
        pat = re.compile(r'pub fn global_init\(\) -> bool \{\n')
        if not pat.search(text):
            raise PatchError('src/common.rs: global_init não encontrado')
        text = pat.sub(global_marker + '\n', text, count=1)
        changed = True

    load_marker = f'pub fn load_custom_client() {{\n    crate::foxxdesk_defaults::apply(); // {MARK}'
    if load_marker not in text:
        pat = re.compile(r'pub fn load_custom_client\(\) \{\n')
        if not pat.search(text):
            raise PatchError('src/common.rs: load_custom_client não encontrado')
        text = pat.sub(load_marker + '\n', text, count=1)
        changed = True

    # Key fallback remains in the parent crate instead of changing config.rs in hbb_common.
    old = '''    if key.is_empty() {\n        key = config::RS_PUB_KEY.to_owned();\n    }'''
    new = f'''    if key.is_empty() {{\n        key = crate::foxxdesk_defaults::PUBLIC_KEY.to_owned(); // {MARK}\n    }}\n    if key.is_empty() {{\n        key = config::RS_PUB_KEY.to_owned();\n    }}'''
    if new not in text:
        if old not in text:
            raise PatchError('src/common.rs: fallback get_key upstream mudou')
        text = text.replace(old, new, 1)
        changed = True
    return text, changed


def patch_client_rs(text: str) -> tuple[str, bool]:
    changed = False

    # PUBLIC_SERVER server list: use the FoxxDesk compiled server instead of hbb_common's public list.
    old_servers = '''                (\n                    check_port(RENDEZVOUS_SERVERS[0], RENDEZVOUS_PORT),\n                    RENDEZVOUS_SERVERS[1..]\n                        .iter()\n                        .map(|x| x.to_string())\n                        .collect(),\n                    true,\n                )'''
    new_servers = f'''                (\n                    check_port(crate::foxxdesk_defaults::RENDEZVOUS_SERVER, RENDEZVOUS_PORT), // {MARK}\n                    Vec::new(),\n                    true,\n                )'''
    if new_servers not in text:
        if old_servers not in text:
            raise PatchError('src/client.rs: bloco PUBLIC_SERVER/RENDEZVOUS_SERVERS upstream mudou')
        text = text.replace(old_servers, new_servers, 1)
        changed = True

    # Secure connection fallback key.
    old_key = '''        let rs_pk = get_rs_pk(if key.is_empty() {\n            config::RS_PUB_KEY\n        } else {\n            key\n        });'''
    new_key = f'''        let rs_pk = get_rs_pk(if key.is_empty() {{\n            crate::foxxdesk_defaults::PUBLIC_KEY // {MARK}\n        }} else {{\n            key\n        }});'''
    if new_key not in text:
        if old_key not in text:
            raise PatchError('src/client.rs: secure_connection key fallback upstream mudou')
        text = text.replace(old_key, new_key, 1)
        changed = True

    # ID@PUBLIC_SERVER key fallback.
    old_public_key = '''            let key = if server == PUBLIC_SERVER {\n                config::RS_PUB_KEY.to_owned()\n            } else {'''
    new_public_key = f'''            let key = if server == PUBLIC_SERVER {{\n                crate::foxxdesk_defaults::PUBLIC_KEY.to_owned() // {MARK}\n            }} else {{'''
    if new_public_key not in text:
        if old_public_key not in text:
            raise PatchError('src/client.rs: PUBLIC_SERVER key fallback upstream mudou')
        text = text.replace(old_public_key, new_public_key, 1)
        changed = True

    return text, changed


def patch_rendezvous_rs(text: str) -> tuple[str, bool]:
    old = '        let mut relay_server = Config::get_option("relay-server");'
    new = f'''        let mut relay_server = Config::get_option("relay-server");\n        if relay_server.is_empty() {{\n            relay_server = crate::foxxdesk_defaults::RELAY_SERVER.to_owned(); // {MARK}\n        }}'''
    if new in text:
        return text, False
    if old not in text:
        raise PatchError('src/rendezvous_mediator.rs: relay-server anchor upstream mudou')
    return text.replace(old, new, 1), True


PATCHERS = {
    'src/lib.rs': patch_lib_rs,
    'src/common.rs': patch_common_rs,
    'src/client.rs': patch_client_rs,
    'src/rendezvous_mediator.rs': patch_rendezvous_rs,
}


def apply_or_check(root: Path, *, apply: bool) -> int:
    cfg, _ = load_config(root, migrate_legacy=True, write_migration=False)
    changed = 0

    owned = root / 'src/foxxdesk_defaults.rs'
    expected = expected_defaults_source(cfg)
    current = owned.read_text(encoding='utf-8', errors='ignore') if owned.is_file() else None
    if current != expected:
        if not apply:
            raise PatchError('src/foxxdesk_defaults.rs ausente/desatualizado; rode o prepare local')
        owned.write_text(expected, encoding='utf-8', newline='\n')
        changed += 1

    for rel, patcher in PATCHERS.items():
        path = root / rel
        if not path.is_file():
            raise PatchError(f'{rel} ausente')
        before = path.read_text(encoding='utf-8', errors='ignore')
        after, did_change = patcher(before)
        if did_change:
            if not apply:
                raise PatchError(f'{rel} ainda não contém o patch runtime FoxxDesk')
            path.write_text(after, encoding='utf-8', newline='\n')
            changed += 1

    mode = 'apply' if apply else 'check'
    print(f'FoxxDesk runtime defaults OK: {changed} arquivo(s) alterado(s) ({SCRIPT_VERSION}, {mode})')
    return changed


def main() -> int:
    p = argparse.ArgumentParser(description='Aplica/valida defaults FoxxDesk no crate principal sem editar hbb_common')
    p.add_argument('--target', default='.')
    mode = p.add_mutually_exclusive_group(required=True)
    mode.add_argument('--apply', action='store_true')
    mode.add_argument('--check', action='store_true')
    args = p.parse_args()
    root = Path(args.target).expanduser().resolve()
    try:
        apply_or_check(root, apply=args.apply)
    except Exception as exc:
        print(f'ERRO runtime defaults: {exc}', file=sys.stderr)
        return 2
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
