// FOXXDESK_RUNTIME_DEFAULTS_V1
// Generated by scripts/foxxdesk_runtime_defaults.py.
// Keep FoxxDesk defaults in the parent crate; do not patch libs/hbb_common.

use hbb_common::config;
use std::sync::Once;

pub const APP_NAME: &str = "FoxxDesk";
pub const RENDEZVOUS_SERVER: &str = "foxxdesk.mguimaraesn.dev";
pub const RELAY_SERVER: &str = "foxxdesk.mguimaraesn.dev";
pub const PUBLIC_KEY: &str = "6WbpsDtYMwUca74qNvNaBfV4pUIGzyXnX1Q8V8fZ8YA=";

static APPLY: Once = Once::new();

pub fn apply() {
    APPLY.call_once(|| {
        *config::APP_NAME.write().unwrap() = APP_NAME.to_owned();
        *config::PROD_RENDEZVOUS_SERVER.write().unwrap() = RENDEZVOUS_SERVER.to_owned();
    });
}
